NMP-Portal/NMP-Portal/Views/Shared/_Layout.cshtml
NMP-Portal/NMP-Portal/Views/Shared/_Layout.cshtml.css
NMP-Portal/NMP-Portal/Views/Shared/_LoginPartial.cshtml
NMP-Portal/NMP-Portal/wwwroot/assets/stylesheets/application.css

Master page updated.. - Feature front end setup

---

NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Controllers/RegisterController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Farm/FarmList.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Name.cshtml
NMP-Portal/NMP-Portal/wwwroot/assets/stylesheets/application.css

i have change the class of PostCode field. Also changed the Index file name to FarmList. 
This branch you may delete.

PostCode input field design modified

---

NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Controllers/RegisterController.cs
NMP-Portal/NMP-Portal/Views/Farm/Name.cshtml

added name action in farm controller.

added name action in farm controller

---

NMP-Portal/NMP-Portal/.config/dotnet-tools.json
NMP-Portal/NMP-Portal/Controllers/AccountController.cs
NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Controllers/HomeController.cs
NMP-Portal/NMP-Portal/Controllers/RegisterController.cs
NMP-Portal/NMP-Portal/Models/User.cs
NMP-Portal/NMP-Portal/NMP-Portal.csproj
NMP-Portal/NMP-Portal/Program.cs
NMP-Portal/NMP-Portal/Properties/ServiceDependencies/DEVNMPINFAW1401 - Web Deploy/profile.arm.json
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Home/Index.cshtml
NMP-Portal/NMP-Portal/Views/Shared/_Layout.cshtml
NMP-Portal/NMP-Portal/Views/Shared/_LoginPartial.cshtml
NMP-Portal/NMP-Portal/appsettings.json

Feature front end setup - Security added

---

NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Models/Farm.cs
NMP-Portal/NMP-Portal/NMP-Portal.csproj
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Farm/Address.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Name.cshtml
NMP-Portal/NMP-Portal/wwwroot/assets/stylesheets/application.css

Feature 351446 front end screens

---

NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Models/Farm.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/FarmViewModel.cs
NMP-Portal/NMP-Portal/Views/Farm/Address.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Elevation.cshtml
NMP-Portal/NMP-Portal/Views/Farm/ManualAddress.cshtml
NMP-Portal/NMP-Portal/Views/Farm/NVZ.cshtml
NMP-Portal/NMP-Portal/Views/Farm/PostcodeError.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Rainfall.cshtml
NMP-Portal/NMP-Portal/Views/Farm/RainfallManual.cshtml

page Validation

---

NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Models/Farm.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx

Validation msg change for postcode and Address 1

Feature validations

---

NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Enums/OrganicProducer.cs
NMP-Portal/NMP-Portal/Models/Farm.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/FarmViewModel.cs
NMP-Portal/NMP-Portal/Views/Farm/Address.cshtml
NMP-Portal/NMP-Portal/Views/Farm/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Elevation.cshtml
NMP-Portal/NMP-Portal/Views/Farm/FarmCheck.cshtml
NMP-Portal/NMP-Portal/Views/Farm/ManualAddress.cshtml
NMP-Portal/NMP-Portal/Views/Farm/NVZ.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Name.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Organic.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Rainfall.cshtml
NMP-Portal/NMP-Portal/Views/Farm/RainfallManual.cshtml

check answer page work in progress

Feature 337862 organic farmer status

---

NMP-Portal/NMP-Portal/Authorization/ValidateTokenHandler.cs
NMP-Portal/NMP-Portal/Authorization/ValidateTokenRequirement.cs
NMP-Portal/NMP-Portal/Controllers/AccountController.cs
NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Helpers/SessionExtensions.cs
NMP-Portal/NMP-Portal/Models/Token.cs
NMP-Portal/NMP-Portal/Program.cs
NMP-Portal/NMP-Portal/Security/SecurityHeadersMiddleware.cs
NMP-Portal/NMP-Portal/ServiceResponses/AddressLookupResponse.cs
NMP-Portal/NMP-Portal/ServiceResponses/AddressLookupResponseHeader.cs
NMP-Portal/NMP-Portal/ServiceResponses/AddressLookupResponseWrapper.cs
NMP-Portal/NMP-Portal/ServiceResponses/Error.cs
NMP-Portal/NMP-Portal/ServiceResponses/Info.cs
NMP-Portal/NMP-Portal/ServiceResponses/ResponseWrapper.cs
NMP-Portal/NMP-Portal/Services/AddressLookupService.cs
NMP-Portal/NMP-Portal/Services/AuthService.cs
NMP-Portal/NMP-Portal/Services/IAddressLookupService.cs
NMP-Portal/NMP-Portal/Services/IService.cs
NMP-Portal/NMP-Portal/Services/Service.cs
NMP-Portal/NMP-Portal/Views/Shared/_Layout.cshtml
NMP-Portal/NMP-Portal/appsettings.json

Need to merge to develop
Branch can be deleted

Calling to service code refactor

---

NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Models/Farm.cs
NMP-Portal/NMP-Portal/Models/FarmData.cs
NMP-Portal/NMP-Portal/Program.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/AddressLookupResponse.cs
NMP-Portal/NMP-Portal/Services/FarmService.cs
NMP-Portal/NMP-Portal/Services/IFarmService.cs
NMP-Portal/NMP-Portal/Views/Farm/Address.cshtml
NMP-Portal/NMP-Portal/Views/Farm/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Elevation.cshtml
NMP-Portal/NMP-Portal/Views/Farm/ManualAddress.cshtml
NMP-Portal/NMP-Portal/Views/Farm/NVZ.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Name.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Organic.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Rainfall.cshtml
NMP-Portal/NMP-Portal/Views/Farm/RainfallManual.cshtml

Feature nmpt 21 check your answers

---

NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Services/FarmService.cs
NMP-Portal/NMP-Portal/Services/IFarmService.cs
NMP-Portal/NMP-Portal/Services/IUserFarmService.cs
NMP-Portal/NMP-Portal/Services/UserFarmService.cs
NMP-Portal/NMP-Portal/Views/Farm/FarmSummary.cshtml
NMP-Portal/NMP-Portal/Views/Home/Index.cshtml

farm name and post code already exist validation on add a farm page done.
Error msg showing if service is not available.
you may delete this branch

Fetaure nmpt 25 add farm completion page

---

NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Models/Farm.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/FarmViewModel.cs
NMP-Portal/NMP-Portal/Views/Farm/Address.cshtml
NMP-Portal/NMP-Portal/Views/Farm/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Elevation.cshtml
NMP-Portal/NMP-Portal/Views/Farm/ManualAddress.cshtml
NMP-Portal/NMP-Portal/Views/Farm/NVZ.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Name.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Organic.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Rainfall.cshtml
NMP-Portal/NMP-Portal/Views/Farm/RainfallManual.cshtml
NMP-Portal/NMP-Portal/Views/Field/AddField.cshtml
NMP-Portal/NMP-Portal/Views/Field/FieldMeasurements.cshtml
NMP-Portal/NMP-Portal/Views/Field/NVZField.cshtml

Is field in NVZ work and added 4 farm model property to save

Nmpt 4 confirm if field is in nvz

---

NMP-Portal/NMP-Portal/Models/Farm.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Home/Index.cshtml

Label updtaes

---

NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Views/Farm/FarmList.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilDateAndPHLevel.cshtml

date validation (validation not confirmed yet)

Feature nmpt 35 6 add the soil analysis for new field

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Field/ManageFarmFields.cshtml

show field success partial work PR

partial work on manage farm field page

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs

Feature bug solving

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Views/Field/AddField.cshtml

back action change on add a field page

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Views/Field/AddField.cshtml

showing the msg if any error occur

Feature solve bug branch

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/CropInfoOneResponse.cs
NMP-Portal/NMP-Portal/Services/CropService.cs
NMP-Portal/NMP-Portal/Services/ICropService.cs
NMP-Portal/NMP-Portal/ViewModels/PlanViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/AnotherCrop.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropFields.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoOne.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearForPlan.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDateQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Crop/VarietyName.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Yield.cshtml
NMP-Portal/NMP-Portal/Views/Crop/YieldQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Field/CheckAnswer.cshtml

Feature yield

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/CropInfoTwoResponse.cs
NMP-Portal/NMP-Portal/Services/CropService.cs
NMP-Portal/NMP-Portal/Services/ICropService.cs
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropFields.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoOne.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoTwo.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearForPlan.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDate.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDateQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Crop/VarietyName.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Yield.cshtml
NMP-Portal/NMP-Portal/Views/Crop/YieldQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Field/ManageFarmFields.cshtml

CropInfo1 and CropInfo2 screen design done

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Enums/Country.cs
NMP-Portal/NMP-Portal/Enums/CropGroup.cs
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml

Feature plan for use of crop

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/FieldViewModel.cs
NMP-Portal/NMP-Portal/Views/Field/AddField.cshtml
NMP-Portal/NMP-Portal/Views/Field/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Field/ElevationField.cshtml
NMP-Portal/NMP-Portal/Views/Field/FieldMeasurements.cshtml
NMP-Portal/NMP-Portal/Views/Field/NVZField.cshtml
NMP-Portal/NMP-Portal/Views/Field/SNSCalculationMethod.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilDateAndPHLevel.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilNutrientValue.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilNutrientValueType.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilReleasingClay.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilType.cshtml
NMP-Portal/NMP-Portal/Views/Field/SulphurDeficient.cshtml

Soil Analysis Older than 5 Years Message work done

#NMPT-213 Soil Analysis Older than 5 Years Message

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Crop/CropFields.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoOne.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoTwo.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDate.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDateQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Yield.cshtml
NMP-Portal/NMP-Portal/Views/Crop/YieldQuestion.cshtml

Feature change label and error message

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Models/CropData.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/HarvestYearPlanResponse.cs
NMP-Portal/NMP-Portal/ServiceResponses/PlanSummaryResponse.cs
NMP-Portal/NMP-Portal/Services/CropService.cs
NMP-Portal/NMP-Portal/Services/ICropService.cs
NMP-Portal/NMP-Portal/ViewModels/PlanViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/Crop/PlansAndRecordsOverview.cshtml

Harvest Year Plan Overview screen and Plan and Records Overview (Summary) screen

Feature nmpt 64 plan for harvest year overview page

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Enums/CropGroup.cs
NMP-Portal/NMP-Portal/Views/Crop/CropGroups.cshtml

grass and other CropGroup disable .

year and confirm(column) data saving in crop table.

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Enums/CropType.cs
NMP-Portal/NMP-Portal/Enums/PotatoCropInfo1.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Services/FieldService.cs
NMP-Portal/NMP-Portal/Services/IFieldService.cs
NMP-Portal/NMP-Portal/Services/SoilService.cs
NMP-Portal/NMP-Portal/ViewModels/PlanViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoOne.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoTwo.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Crop/VarietyName.cshtml

Feature check your answer page

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/ErrorController.cs
NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/NMP-Portal.csproj
NMP-Portal/NMP-Portal/Program.cs
NMP-Portal/NMP-Portal/Security/CustomerIdentity.cs
NMP-Portal/NMP-Portal/Services/AddressLookupService.cs
NMP-Portal/NMP-Portal/Services/CropService.cs
NMP-Portal/NMP-Portal/Services/FarmService.cs
NMP-Portal/NMP-Portal/Services/FieldService.cs
NMP-Portal/NMP-Portal/Services/Service.cs
NMP-Portal/NMP-Portal/Services/SoilService.cs
NMP-Portal/NMP-Portal/Services/UserFarmService.cs
NMP-Portal/NMP-Portal/Views/Shared/_Layout.cshtml
NMP-Portal/NMP-Portal/appsettings.json

Customer Identity Implementation

Customer Identity Implementation

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Models/Crop.cs
NMP-Portal/NMP-Portal/Models/HarvestYearPlanData.cs
NMP-Portal/NMP-Portal/Models/HarvestYearPlans.cs
NMP-Portal/NMP-Portal/Models/ManagementPeriod.cs
NMP-Portal/NMP-Portal/Models/Recommendation.cs
NMP-Portal/NMP-Portal/Models/RecommendationComment.cs
NMP-Portal/NMP-Portal/Models/RecommendationData.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/RecommendationHeader.cs
NMP-Portal/NMP-Portal/Services/CropService.cs
NMP-Portal/NMP-Portal/Services/FieldService.cs
NMP-Portal/NMP-Portal/Services/ICropService.cs
NMP-Portal/NMP-Portal/Services/IFieldService.cs
NMP-Portal/NMP-Portal/ViewModels/CropViewModel.cs
NMP-Portal/NMP-Portal/ViewModels/RecommendationViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml
NMP-Portal/NMP-Portal/wwwroot/assets/stylesheets/application.css

Feature recommendations field level

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs

cancel button functionality done

---

NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Services/FarmService.cs
NMP-Portal/NMP-Portal/Services/IFarmService.cs

Fetch farm by orgId

---

NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Models/Organisation.cs
NMP-Portal/NMP-Portal/Models/User.cs
NMP-Portal/NMP-Portal/Models/UserData.cs
NMP-Portal/NMP-Portal/Program.cs
NMP-Portal/NMP-Portal/Security/CustomerIdentity.cs
NMP-Portal/NMP-Portal/Services/AuthService.cs
NMP-Portal/NMP-Portal/Services/IAuthService.cs

Add Or Update User

---

NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Models/Farm.cs

Farm level Bug solve

---

NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml
NMP-Portal/NMP-Portal/wwwroot/assets/stylesheets/application.css

Recommendation design bug has been resolved.

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Models/ManureType.cs
NMP-Portal/NMP-Portal/Models/OrganicManure.cs
NMP-Portal/NMP-Portal/Program.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/CommonResponse.cs
NMP-Portal/NMP-Portal/ServiceResponses/OrganicManureCropTypeResponse.cs
NMP-Portal/NMP-Portal/ServiceResponses/OrganicManureFieldResponse.cs
NMP-Portal/NMP-Portal/Services/IOrganicManureService.cs
NMP-Portal/NMP-Portal/Services/OrganicManureService.cs
NMP-Portal/NMP-Portal/ViewModels/OrganicManureViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureType.cshtml

Feature which fields are you planning organic material

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Models/ManureType.cs
NMP-Portal/NMP-Portal/Models/OrganicManure.cs
NMP-Portal/NMP-Portal/Services/IOrganicManureService.cs
NMP-Portal/NMP-Portal/Services/OrganicManureService.cs
NMP-Portal/NMP-Portal/ViewModels/OrganicManureViewModel.cs
NMP-Portal/NMP-Portal/Views/OrganicManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureType.cshtml

Feature manure type

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Models/OrganicManure.cs
NMP-Portal/NMP-Portal/Program.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/OrganicManureCropTypeResponse.cs
NMP-Portal/NMP-Portal/ServiceResponses/OrganicManureFieldResponse.cs
NMP-Portal/NMP-Portal/Services/IOrganicManureService.cs
NMP-Portal/NMP-Portal/Services/OrganicManureService.cs
NMP-Portal/NMP-Portal/ViewModels/OrganicManureViewModel.cs
NMP-Portal/NMP-Portal/Views/OrganicManure/DefaultNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureApplyingDate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureType.cshtml

Application date and default nutrient page

Feature nmpt 266 date to apply organic material in the fields

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Models/OrganicManure.cs
NMP-Portal/NMP-Portal/Views/OrganicManure/DefaultNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureApplyingDate.cshtml

if SO3 and MgO is null then set to 0

Feature display latest manure list

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Models/OrganicManure.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/OrganicManureViewModel.cs
NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationRateMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/AreaQuantity.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ConditionsAffectingNutrients.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/DefaultNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/EnterDefaultNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationDelay.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualApplicationRate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureApplyingDate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureType.cshtml

Feature enter default nutrient value

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx

bug resolved NMPT-418, NMPT-424

Bug solving

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Models/OrganicManure.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Services/IOrganicManureService.cs
NMP-Portal/NMP-Portal/Services/OrganicManureService.cs
NMP-Portal/NMP-Portal/ViewModels/OrganicManureViewModel.cs
NMP-Portal/NMP-Portal/Views/Farm/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Field/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationRateMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/AreaQuantity.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ConditionsAffectingNutrients.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/DefaultNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationDelay.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualApplicationRate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureApplyingDate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureType.cshtml

save data into Organic manure table

Feature check answer page

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Models/HarvestYearPlanFields.cs
NMP-Portal/NMP-Portal/Models/HarvestYearPlans.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/HarvestYearPlanResponse.cs
NMP-Portal/NMP-Portal/ViewModels/OrganicManureViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationRateMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/AreaQuantity.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ConditionsAffectingNutrients.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/DefaultNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationDelay.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualApplicationRate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureApplyingDate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureType.cshtml

Organic manure success page and some little modifications done on check answer page

Organic manure success page

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Models/OrganicManure.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/OrganicManureViewModel.cs
NMP-Portal/NMP-Portal/ViewModels/RecommendationViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationRateMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/AreaQuantity.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ConditionsAffectingNutrients.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/DefaultNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationDelay.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualApplicationRate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureApplyingDate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureType.cshtml

Feature add organic material from a specific field task done

Feature add organic material from a specific field

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/OrganicManureViewModel.cs
NMP-Portal/NMP-Portal/Views/OrganicManure/AutumnCropNitrogenUptake.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ConditionsAffectingNutrients.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/SoilDrainageEndDate.cshtml

Conditions page peding work and  change crop uptake work

Feature nmpt 275 conditions at the time of application

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Models/OrganicManure.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Services/IOrganicManureService.cs
NMP-Portal/NMP-Portal/Services/OrganicManureService.cs
NMP-Portal/NMP-Portal/ViewModels/OrganicManureViewModel.cs
NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationRateMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/AreaQuantity.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/AutumnCropNitrogenUptake.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ConditionsAffectingNutrients.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/DefaultNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/EffectiveRainfall.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/EffectiveRainfallManual.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationDelay.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualApplicationRate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureType.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/RainfallWithinSixHour.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/SoilDrainageEndDate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/TopsoilMoisture.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/Windspeed.cshtml

all the changes functionality on conditions page covered

Feature nmpt 469 what is the end of drainage date

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureApplyingDate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/SoilDrainageEndDate.cshtml

NMPT-477 and NMPT-476 task complete

Feature change your answers journey manure type

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/OrganicManureViewModel.cs
NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationRateMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/AreaQuantity.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/AutumnCropNitrogenUptake.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ConditionsAffectingNutrients.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/DefaultNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/EffectiveRainfall.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/EffectiveRainfallManual.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationDelay.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualApplicationRate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureApplyingDate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureType.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/NutrientValuesStoreForFuture.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/RainfallWithinSixHour.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/SoilDrainageEndDate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/TopsoilMoisture.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/Windspeed.cshtml

Feature change your answers journey application rate entry option change

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Models/OrganicManure.cs
NMP-Portal/NMP-Portal/Views/OrganicManure/AreaQuantity.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualApplicationRate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureApplyingDate.cshtml

Feature change your answers journey fields

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/ViewModels/OrganicManureViewModel.cs
NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationDelay.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationMethod.cshtml

Feature change your answers journey application method

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/ViewModels/OrganicManureViewModel.cs
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationDelay.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureApplyingDate.cshtml

NMPT-526 and NMPT-527 user story done

Feature change your answer journey for incoporation method

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/ViewModels/OrganicManureViewModel.cs
NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationRateMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/AreaQuantity.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/DefaultNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualApplicationRate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/NutrientValuesStoreForFuture.cshtml

NMPT-534 user story done

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs

little modification for NMPT-534 user story

Feature change journey for default nutrientt values

---

NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Models/FertiliserManures.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/InOrganicManureDurationResponse.cs
NMP-Portal/NMP-Portal/Services/FertiliserManureService.cs
NMP-Portal/NMP-Portal/Services/IFertiliserManureService.cs
NMP-Portal/NMP-Portal/ViewModels/FertiliserManureViewModel.cs
NMP-Portal/NMP-Portal/Views/FertiliserManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/InOrgnaicManureDuration.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/NutrientValues.cshtml

Feature when do you plan to spread inorganic fertiliser

---

NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/FertiliserManureViewModel.cs
NMP-Portal/NMP-Portal/Views/FertiliserManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/InOrgnaicManureDuration.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/NutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/QuestionForSpreadInorganicFertiliser.cshtml

Feature how much of each nutrient do you plan

---

NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Models/FertiliserManure.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/FertiliserManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/InOrgnaicManureDuration.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/NutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/QuestionForSpreadInorganicFertiliser.cshtml

Feature check your answer

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/FieldViewModel.cs
NMP-Portal/NMP-Portal/Views/Field/AddField.cshtml
NMP-Portal/NMP-Portal/Views/Field/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Field/ElevationField.cshtml
NMP-Portal/NMP-Portal/Views/Field/FieldMeasurements.cshtml
NMP-Portal/NMP-Portal/Views/Field/NVZField.cshtml
NMP-Portal/NMP-Portal/Views/Field/SNSCalculationMethod.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilDateAndPHLevel.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilNutrientValue.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilNutrientValueType.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilReleasingClay.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilType.cshtml
NMP-Portal/NMP-Portal/Views/Field/SulphurDeficient.cshtml

Feature nmpt575 user story

---

NMP-Portal/NMP-Portal/Views/Field/SNSAppliedQuestion.cshtml

Feature nmpt576 user story

---

NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Field/CheckAnswer.cshtml

Feature check your answers page update after onboarding changes

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Models/HarvestYear.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/PlanSummaryResponse.cs
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/PlansAndRecordsOverview.cshtml

Feature nmpt577 user story

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Services/IOrganicManureService.cs
NMP-Portal/NMP-Portal/Services/OrganicManureService.cs
NMP-Portal/NMP-Portal/ViewModels/OrganicManureViewModel.cs
NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationRateMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/AreaQuantity.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualApplicationRate.cshtml

NMPT-582 and NMPT-492 user story done

Feature nmpt582 user story

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Models/Crop.cs

bug nmpt607 resolved and some modification related to NMPT-493

Feature bug nmpt607

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Services/IOrganicManureService.cs
NMP-Portal/NMP-Portal/Services/OrganicManureService.cs

little modification

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Helpers/OrganicManureNMaxLimitLogic.cs
NMP-Portal/NMP-Portal/Helpers/WarningMessage.cs
NMP-Portal/NMP-Portal/Services/FertiliserManureService.cs
NMP-Portal/NMP-Portal/Services/IFertiliserManureService.cs

Feature nmpt587 user story

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs

Warning msg showing when application rate is changing.

---

NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Helpers/WarningMessage.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/FertiliserManureViewModel.cs
NMP-Portal/NMP-Portal/Views/FertiliserManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/InOrgnaicManureDuration.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/NutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/QuestionForSpreadInorganicFertiliser.cshtml

NMPT-606, 497,603,516 user story done

Feature nmpt606

---

NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Helpers/WarningMessage.cs

Code refactor for warning messages

Feature code refactor for warning messages

---

NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Enums/InOrganicManureDurations.cs
NMP-Portal/NMP-Portal/Helpers/WarningMessage.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/FertiliserManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/InOrgnaicManureDuration.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/NutrientValues.cshtml

NMPT-604 and NMPT-515 user story done

Festure nmpt604

---

NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Helpers/WarningMessage.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/NutrientValues.cshtml

nmpt-605 and 514 user story done

Feature nmpt605

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/FieldViewModel.cs
NMP-Portal/NMP-Portal/Views/Field/AddField.cshtml
NMP-Portal/NMP-Portal/Views/Field/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Field/CurrentCropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Field/FieldMeasurements.cshtml
NMP-Portal/NMP-Portal/Views/Field/NVZField.cshtml
NMP-Portal/NMP-Portal/Views/Field/SampleForSoilMineralNitrogen.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilDateAndPHLevel.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilNutrientValue.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilNutrientValueType.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilReleasingClay.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilType.cshtml
NMP-Portal/NMP-Portal/Views/Field/SulphurDeficient.cshtml

NMPT-443 user story done

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/FieldViewModel.cs
NMP-Portal/NMP-Portal/Views/Field/AddField.cshtml
NMP-Portal/NMP-Portal/Views/Field/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Field/CurrentCropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Field/CurrentCropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Field/FieldMeasurements.cshtml
NMP-Portal/NMP-Portal/Views/Field/NVZField.cshtml
NMP-Portal/NMP-Portal/Views/Field/SNSAppliedQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Field/SampleForSoilMineralNitrogen.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilDateAndPHLevel.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilNutrientValue.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilNutrientValueType.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilReleasingClay.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilType.cshtml
NMP-Portal/NMP-Portal/Views/Field/SulphurDeficient.cshtml

Fetaure nmpt443

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Enums/SNSCategories.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/CropTypeLinkingResponse.cs
NMP-Portal/NMP-Portal/ViewModels/FieldViewModel.cs
NMP-Portal/NMP-Portal/Views/Field/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Field/CurrentCropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Field/CurrentCropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Field/ElevationField.cshtml
NMP-Portal/NMP-Portal/Views/Field/FieldMeasurements.cshtml
NMP-Portal/NMP-Portal/Views/Field/NVZField.cshtml
NMP-Portal/NMP-Portal/Views/Field/SNSAppliedQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Field/SampleDepth.cshtml
NMP-Portal/NMP-Portal/Views/Field/SampleForSoilMineralNitrogen.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilDateAndPHLevel.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilMineralNitrogenAnalysisResults.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilNutrientValue.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilNutrientValueType.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilReleasingClay.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilType.cshtml
NMP-Portal/NMP-Portal/Views/Field/SulphurDeficient.cshtml

NMPT-444 user story done
You may delete this branch.

NMPT-444 user story done

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/FertiliserManure/InOrgnaicManureDuration.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/NutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/Field/AddField.cshtml
NMP-Portal/NMP-Portal/Views/Field/CalculateNitrogenInCurrentCropQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Field/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Field/CurrentCropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Field/CurrentCropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Field/ElevationField.cshtml
NMP-Portal/NMP-Portal/Views/Field/EstimateOfNitrogenMineralisationQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Field/FieldMeasurements.cshtml
NMP-Portal/NMP-Portal/Views/Field/GrowthAreaIndexOrCropHeight.cshtml
NMP-Portal/NMP-Portal/Views/Field/NVZField.cshtml
NMP-Portal/NMP-Portal/Views/Field/NumberOfShoots.cshtml
NMP-Portal/NMP-Portal/Views/Field/SNSAppliedQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Field/SampleDepth.cshtml
NMP-Portal/NMP-Portal/Views/Field/SampleForSoilMineralNitrogen.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilDateAndPHLevel.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilMineralNitrogenAnalysisResults.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilNutrientValue.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilNutrientValueType.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilReleasingClay.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilType.cshtml
NMP-Portal/NMP-Portal/Views/Field/SulphurDeficient.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualApplicationRate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureApplyingDate.cshtml

NMPT-477 user story done and warning msg change also done

Feature nmpt447

---

NMP-Portal/NMP-Portal/Views/Field/SampleDepth.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilMineralNitrogenAnalysisResults.cshtml

Bug resolved

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Services/FieldService.cs
NMP-Portal/NMP-Portal/ViewModels/FieldViewModel.cs
NMP-Portal/NMP-Portal/Views/Field/AddField.cshtml
NMP-Portal/NMP-Portal/Views/Field/CalculateNitrogenInCurrentCropQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Field/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Field/CurrentCropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Field/CurrentCropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Field/ElevationField.cshtml
NMP-Portal/NMP-Portal/Views/Field/EstimateOfNitrogenMineralisationQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Field/FieldMeasurements.cshtml
NMP-Portal/NMP-Portal/Views/Field/GrowthAreaIndexOrCropHeight.cshtml
NMP-Portal/NMP-Portal/Views/Field/NVZField.cshtml
NMP-Portal/NMP-Portal/Views/Field/NumberOfShoots.cshtml
NMP-Portal/NMP-Portal/Views/Field/SNSAppliedQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Field/SampleDepth.cshtml
NMP-Portal/NMP-Portal/Views/Field/SampleForSoilMineralNitrogen.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilDateAndPHLevel.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilMineralNitrogenAnalysisResults.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilNutrientValue.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilNutrientValueType.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilReleasingClay.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilType.cshtml
NMP-Portal/NMP-Portal/Views/Field/SulphurDeficient.cshtml

Feature nmpt461

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/FieldViewModel.cs
NMP-Portal/NMP-Portal/Views/Field/AdjustmentValue.cshtml
NMP-Portal/NMP-Portal/Views/Field/CalculateNitrogenInCurrentCropQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Field/CalculateSoilNitrogenMineralisation.cshtml
NMP-Portal/NMP-Portal/Views/Field/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropHeight.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Field/CurrentCropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Field/CurrentCropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Field/ElevationField.cshtml
NMP-Portal/NMP-Portal/Views/Field/EstimateOfNitrogenMineralisationQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Field/FieldMeasurements.cshtml
NMP-Portal/NMP-Portal/Views/Field/GreenAreaIndex.cshtml
NMP-Portal/NMP-Portal/Views/Field/GreenAreaIndexOrCropHeightQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Field/NVZField.cshtml
NMP-Portal/NMP-Portal/Views/Field/NumberOfShoots.cshtml
NMP-Portal/NMP-Portal/Views/Field/SNSAppliedQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Field/SampleDepth.cshtml
NMP-Portal/NMP-Portal/Views/Field/SampleForSoilMineralNitrogen.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilDateAndPHLevel.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilMineralNitrogenAnalysisResults.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilNutrientValue.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilNutrientValueType.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilOrganicMatter.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilReleasingClay.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilType.cshtml

Feature nmpt463

---

NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Field/SoilMineralNitrogenAnalysisResults.cshtml

lable change according to user story

lable change according to user story

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Services/IOrganicManureService.cs
NMP-Portal/NMP-Portal/Services/OrganicManureService.cs
NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationMethod.cshtml

Feature calling manner api url

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs

these all are croptype will be  used for scotland
You may delete this branch

Feature extra crop type that not in sns category

---

NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Services/FarmService.cs

useing manner api for rainfall

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs

using cropTypeLinking api for ManureCropType.

use cropTypeLinking api for ManureCropType

---

NMP-Portal/NMP-Portal/Helpers/WarningMessage.cs

Error fixed

---

NMP-Portal/NMP-Portal/Views/Field/CheckAnswer.cshtml

Feature nmpt660

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs

issue resolved

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs

soil end drange date issue resolved

soil end drange date issue resolved

---

NMP-Portal/NMP-Portal/Controllers/SoilAnalysisController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/SoilAnalysisViewModel.cs
NMP-Portal/NMP-Portal/Views/Field/FieldSoilAnalysisDetail.cshtml
NMP-Portal/NMP-Portal/Views/SoilAnalysis/ChangeSoilAnalysis.cshtml
NMP-Portal/NMP-Portal/Views/SoilAnalysis/Date.cshtml
NMP-Portal/NMP-Portal/Views/SoilAnalysis/SoilAnalysisDetail.cshtml
NMP-Portal/NMP-Portal/Views/SoilAnalysis/SoilNutrientValue.cshtml
NMP-Portal/NMP-Portal/Views/SoilAnalysis/SoilNutrientValueType.cshtml
NMP-Portal/NMP-Portal/Views/SoilAnalysis/SuccessPage.cshtml
NMP-Portal/NMP-Portal/Views/SoilAnalysis/SulphurDeficient.cshtml

NMPT-555 user story

---

NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/SoilAnalysis/Date.cshtml

example date change

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/FertiliserManureViewModel.cs
NMP-Portal/NMP-Portal/Views/FertiliserManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/InOrgnaicManureDuration.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/NutrientValues.cshtml
NMP-Portal/NMP-Portal/appsettings.json

Feature nmpt637

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Models/FertiliserManure.cs
NMP-Portal/NMP-Portal/Models/Recommendation.cs
NMP-Portal/NMP-Portal/Models/RecommendationComment.cs
NMP-Portal/NMP-Portal/Models/RecommendationData.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/HarvestYearPlanResponse.cs
NMP-Portal/NMP-Portal/Services/FertiliserManureService.cs
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/Crop/PlansAndRecordsOverview.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml
NMP-Portal/NMP-Portal/Views/Farm/FarmSummary.cshtml
NMP-Portal/NMP-Portal/Views/Field/ManageFarmFields.cshtml

NMPT-712 and NMPT-713 user stories done

Feature nmpt712

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Models/AutumnCropNitrogenUptakeDetail.cs
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml

bug resolving for organic manure

bug resolving..

---

NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Services/FertiliserManureService.cs
NMP-Portal/NMP-Portal/Services/IFertiliserManureService.cs

NMPT771 bug has been resolved.

bug has been resolved.

---

NMP-Portal/NMP-Portal/Controllers/FarmController.cs

farm update modification

---

NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/ViewModels/FertiliserManureViewModel.cs
NMP-Portal/NMP-Portal/Views/FertiliserManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/InOrgnaicManureDuration.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/NutrientValues.cshtml

Feature bug on fertiliser screen

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Services/FarmService.cs
NMP-Portal/NMP-Portal/ViewModels/PlanViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/wwwroot/assets/stylesheets/application.css

Feature nm pt718

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Controllers/SoilAnalysisController.cs

Feature nmpt784

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Enums/FarmCountry.cs
NMP-Portal/NMP-Portal/Enums/RB209Country.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Models/Country.cs
NMP-Portal/NMP-Portal/Models/Farm.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Services/FarmService.cs
NMP-Portal/NMP-Portal/Services/IFarmService.cs
NMP-Portal/NMP-Portal/Views/Farm/Country.cshtml
NMP-Portal/NMP-Portal/Views/Farm/FarmingRules.cshtml

Feature nmpt776

---

NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Farm/PostCode.cshtml

NMPT 821 user story done

---

NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/FarmViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Address.cshtml
NMP-Portal/NMP-Portal/Views/Farm/AddressNotFound.cshtml
NMP-Portal/NMP-Portal/Views/Farm/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Country.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Elevation.cshtml
NMP-Portal/NMP-Portal/Views/Farm/FarmDetails.cshtml
NMP-Portal/NMP-Portal/Views/Farm/FarmingRules.cshtml
NMP-Portal/NMP-Portal/Views/Farm/LastHarvestYear.cshtml
NMP-Portal/NMP-Portal/Views/Farm/ManualAddress.cshtml
NMP-Portal/NMP-Portal/Views/Farm/NVZ.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Name.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Organic.cshtml
NMP-Portal/NMP-Portal/Views/Farm/PostCode.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Rainfall.cshtml
NMP-Portal/NMP-Portal/Views/Farm/RainfallManual.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/NutrientValues.cshtml

Feaure nmpt822

---

NMP-Portal/NMP-Portal/NMP-Portal.csproj

Package downgrade

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs

nmpt-905 user story done......

modification for nmpt-905 user story

---

NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/ReportViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml
NMP-Portal/NMP-Portal/Views/Report/ExportFields.cshtml
NMP-Portal/NMP-Portal/wwwroot/assets/stylesheets/application.css

Feature nmpt889

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs

NMPT-937 bug resolve

---

NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/CropAndFieldReportResponse.cs
NMP-Portal/NMP-Portal/ServiceResponses/CropReportResponse.cs
NMP-Portal/NMP-Portal/ServiceResponses/FarmReportResponse.cs
NMP-Portal/NMP-Portal/ServiceResponses/FieldAndCropReportResponse.cs
NMP-Portal/NMP-Portal/ServiceResponses/RecommendationReportResponse.cs
NMP-Portal/NMP-Portal/ServiceResponses/SoilAnalysisAndSNSanalysisReportResponse.cs
NMP-Portal/NMP-Portal/ServiceResponses/SoilAnalysisReportResponse.cs
NMP-Portal/NMP-Portal/Services/FieldService.cs
NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml
NMP-Portal/NMP-Portal/wwwroot/assets/stylesheets/application.css

Feature nmpt893

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/FieldAndCropReportResponse.cs
NMP-Portal/NMP-Portal/ViewModels/FieldViewModel.cs
NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml

nmpt-894 user story done

---

NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/CropReportResponse.cs
NMP-Portal/NMP-Portal/ServiceResponses/FieldAndCropReportResponse.cs
NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml

nmpt-895 user story done

---

NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml

nmpt-896 user story done

---

NMP-Portal/NMP-Portal/Models/OrganicManureData.cs
NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml

NMPT-897 and NMPT-898 complete

NMPT-897 and NMPT-898 done

---

NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/FieldAndCropReportResponse.cs
NMP-Portal/NMP-Portal/ServiceResponses/SoilAnalysisAndSNSanalysisReportResponse.cs
NMP-Portal/NMP-Portal/ServiceResponses/SoilAnalysisReportResponse.cs
NMP-Portal/NMP-Portal/ServiceResponses/SoilDetailsResponse.cs
NMP-Portal/NMP-Portal/Services/FieldService.cs
NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml

NMPt-900 done

---

NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Enums/Nutrients.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/RecommendationReportHeaderResponse.cs
NMP-Portal/NMP-Portal/ServiceResponses/RecommendationReportResponse.cs
NMP-Portal/NMP-Portal/ViewModels/ReportViewModel.cs
NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml
NMP-Portal/NMP-Portal/Views/Shared/_Layout.cshtml

NMPt-901 user story done

---

NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml
NMP-Portal/NMP-Portal/wwwroot/assets/stylesheets/application.css

NMPT-891 user story done

---

NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml

some changes for recommandation table (Print screen)

some changes

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Models/MeasurementData.cs
NMP-Portal/NMP-Portal/appsettings.json

Feature nmpt961

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Models/Field.cs
NMP-Portal/NMP-Portal/Models/OrganicManure.cs
NMP-Portal/NMP-Portal/ServiceResponses/MannerCalculateNutrientResponse.cs
NMP-Portal/NMP-Portal/Services/CropService.cs
NMP-Portal/NMP-Portal/Services/ICropService.cs
NMP-Portal/NMP-Portal/Services/IOrganicManureService.cs
NMP-Portal/NMP-Portal/Services/OrganicManureService.cs
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml

Feature calling manner api

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationRateMethod.cshtml
NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml

Feature nmpt982

---

NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml
NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml

remove sodium on print screen and Recommendation

Feature remove sodium

---

NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Helpers/WarningMessage.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/appsettings.json

Feature nmpt 963 content corrections

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs

Feature nmpt983

---

NMP-Portal/NMP-Portal/Views/Shared/_Layout.cshtml
NMP-Portal/NMP-Portal/wwwroot/assets/stylesheets/application.css

Feature modification in printing

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/OrganicManureViewModel.cs
NMP-Portal/NMP-Portal/Views/Farm/Address.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationRateMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/AreaQuantity.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/AutumnCropNitrogenUptake.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/AutumnCropNitrogenUptakeDetail.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ConditionsAffectingNutrients.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/DefaultNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/EffectiveRainfall.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/EffectiveRainfallManual.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationDelay.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationMethod.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualApplicationRate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureApplyingDate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureGroup.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManureType.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/NutrientValuesStoreForFuture.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/OtherMaterialName.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/RainfallWithinSixHour.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/SoilDrainageEndDate.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/TopsoilMoisture.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/Windspeed.cshtml

nmpt984 and nmpt-986 user story done

Feature nmpt984

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs

minor change

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Enums/CropInfoOne.cs
NMP-Portal/NMP-Portal/Helpers/OrganicManureNMaxLimitLogic.cs
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/DefaultNutrientValues.cshtml

bug1009 and bug 1010  has been resolved.

Feature bug1009

---

NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Views/Farm/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Farm/FarmDetails.cshtml
NMP-Portal/NMP-Portal/Views/Farm/FarmRemove.cshtml

changes for climate data postcode

Feature nmpt1020

---

NMP-Portal/NMP-Portal/Controllers/FarmController.cs

BUg 1065 resolved

---

NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Controllers/SoilAnalysisController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/SoilAnalysis/Date.cshtml
NMP-Portal/NMP-Portal/Views/SoilAnalysis/SoilNutrientValue.cshtml
NMP-Portal/NMP-Portal/Views/SoilAnalysis/SoilNutrientValueType.cshtml

NMPT-1022, NMPT-1066,NMPT-1062 done

Feature nmpt1022

---

NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/SoilAnalysis/SoilAnalysisDetail.cshtml

Feature nmpt1025 user story

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Controllers/SoilAnalysisController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Services/ISoilAnalysisService.cs
NMP-Portal/NMP-Portal/Services/SoilAnalysisService.cs
NMP-Portal/NMP-Portal/ViewModels/SoilAnalysisViewModel.cs
NMP-Portal/NMP-Portal/Views/Field/FieldSoilAnalysisDetail.cshtml
NMP-Portal/NMP-Portal/Views/SoilAnalysis/ChangeSoilAnalysis.cshtml
NMP-Portal/NMP-Portal/Views/SoilAnalysis/SoilAnalysisDetail.cshtml
NMP-Portal/NMP-Portal/Views/SoilAnalysis/SoilNutrientValue.cshtml
NMP-Portal/NMP-Portal/appsettings.json

Feature nmpt1023

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/SoilAnalysisController.cs
NMP-Portal/NMP-Portal/Views/Field/FieldSoilAnalysisDetail.cshtml

Feature nmpt1041

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Controllers/SoilAnalysisController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Services/ISoilAnalysisService.cs
NMP-Portal/NMP-Portal/Services/SoilAnalysisService.cs
NMP-Portal/NMP-Portal/ViewModels/SoilAnalysisViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Field/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/SoilAnalysis/ChangeSoilAnalysis.cshtml
NMP-Portal/NMP-Portal/Views/SoilAnalysis/RemoveSoilAnalysis.cshtml

remove soil analysis story done

Feature remove soil analysis

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml

NMPT1074 done

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Models/Crop.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/PlanViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropFields.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropGroupName.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoOne.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoTwo.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearForPlan.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDate.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDateQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Crop/VarietyName.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Yield.cshtml
NMP-Portal/NMP-Portal/Views/Crop/YieldQuestion.cshtml

Feature nmpt652

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Models/HarvestYearPlanFields.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/HarvestYearPlanResponse.cs
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropGroupName.cshtml
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/Crop/VarietyName.cshtml
NMP-Portal/NMP-Portal/wwwroot/assets/stylesheets/application.css

Feature nmpt653

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Models/HarvestYearPlanFields.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/Crop/RemoveCropGroup.cshtml

changes for NMPT653 and some for 1032

Feature nmpt1032

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Models/Recommendation.cs
NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml

Feature changes for recommendations

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/HarvestYearPlanResponse.cs
NMP-Portal/NMP-Portal/ServiceResponses/InorganicFertiliserResponse.cs
NMP-Portal/NMP-Portal/Services/CropService.cs
NMP-Portal/NMP-Portal/Services/FertiliserManureService.cs
NMP-Portal/NMP-Portal/Services/ICropService.cs
NMP-Portal/NMP-Portal/Services/IFertiliserManureService.cs
NMP-Portal/NMP-Portal/ViewModels/PlanViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/DeletePlanOrganicAndFertiliser.cshtml
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/Crop/PlansAndRecordsOverview.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml
NMP-Portal/NMP-Portal/Views/Crop/RemoveCropGroup.cshtml
NMP-Portal/NMP-Portal/Views/Farm/FarmSummary.cshtml
NMP-Portal/NMP-Portal/wwwroot/assets/stylesheets/application.css

remove crop group name stories done

Feature nmpt1036

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Models/FertiliserManure.cs
NMP-Portal/NMP-Portal/ViewModels/FieldViewModel.cs
NMP-Portal/NMP-Portal/ViewModels/PlanViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml
NMP-Portal/NMP-Portal/Views/Crop/RemoveCrop.cshtml

Little changes for crop group name

Little changes

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Models/HarvestYearPlans.cs
NMP-Portal/NMP-Portal/Models/OrganicManureData.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/OrganicManureResponse.cs
NMP-Portal/NMP-Portal/Services/IOrganicManureService.cs
NMP-Portal/NMP-Portal/Services/OrganicManureService.cs
NMP-Portal/NMP-Portal/ViewModels/PlanViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/DeletePlanOrganicAndFertiliser.cshtml
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/Crop/OrganicManureFieldRemove.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml

remove organic manure stories done

Feature nmpt1027

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Models/FertiliserManure.cs
NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml

changes for fertliser

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs

bug resolve

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Models/ExcessRainfalls.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/CommonResponse.cs
NMP-Portal/NMP-Portal/Services/FarmService.cs
NMP-Portal/NMP-Portal/Services/IFarmService.cs
NMP-Portal/NMP-Portal/ViewModels/PlanViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/ExcessWinterRainFall.cshtml
NMP-Portal/NMP-Portal/Views/Crop/ExcessWinterRainfallCheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/Crop/UpdateExcessWinterRainfall.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/EffectiveRainfallManual.cshtml

NMPT-1045, NMPT-1046, NMPT-1017 done

Feature nmpt1017

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Crop/VarietyName.cshtml

Feature nmpt1129

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs

Feature some bugs

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Views/Field/FieldSoilAnalysisDetail.cshtml

Feature nmpt1143

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Views/Field/FieldSoilAnalysisDetail.cshtml

Feature nmpt1144

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Controllers/SoilAnalysisController.cs
NMP-Portal/NMP-Portal/Models/OrganicManure.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/OrganicManureViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualApplicationRate.cshtml

NMPT-1149,NMPT-1146,NMPT-1148 and NMPT-1152 done

Feature nmpt1146

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Models/Step2.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/FieldViewModel.cs
NMP-Portal/NMP-Portal/Views/Field/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Field/FieldSoilAnalysisDetail.cshtml
NMP-Portal/NMP-Portal/Views/Field/GreenAreaIndex.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilNitrogenSupplyIndex.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualNutrientValues.cshtml

NMPT-1160, NMPT-1158, NMPT-1164,NMPT-1154,NMPT-1153,NMPT-1150 Done

Feature nmpt1150

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Field/SoilOrganicMatter.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/DefaultNutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualNutrientValues.cshtml

NMPT-1157, NMPT-1156, NMPT-1145 done

NMPT-1157, NMPT-1156, NMPT-1145 user story

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/FertiliserManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Field/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/DefaultNutrientValues.cshtml

Feature nmpt1162

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Controllers/SoilAnalysisController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/FieldViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml
NMP-Portal/NMP-Portal/Views/Field/FieldSoilAnalysisDetail.cshtml
NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml

NMPT-1203 and NMPT-1204 user story done

done both stories

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/SnsAnalysisController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Models/SnsAnalysis.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Services/FarmService.cs
NMP-Portal/NMP-Portal/Services/ISnsAnalysisService.cs
NMP-Portal/NMP-Portal/Services/SnsAnalysisService.cs
NMP-Portal/NMP-Portal/ViewModels/SnsAnalysisViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/RemoveSnsAnalysis.cshtml

Feature nmpt1194

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/ViewModels/PlanViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/CropGroupName.cshtml

Feature bug1226

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Services/CropService.cs
NMP-Portal/NMP-Portal/Services/ICropService.cs
NMP-Portal/NMP-Portal/Views/Crop/UpdateCropGroupNameCheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/VarietyName.cshtml

Feature nmpt1137

---

NMP-Portal/NMP-Portal/Controllers/SnsAnalysisController.cs
NMP-Portal/NMP-Portal/Views/SnsAnalysis/SampleDepth.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/SoilNitrogenSupplyIndex.cshtml

back button on Soil Nitrogen Supply Index page for sns category Vegetable

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/FertiliserManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/ManualNutrientValues.cshtml

nmpt-1258, NMPT1254,NMPT1255 DONE

nmpt-1258, NMPT1254,NMPT1255 DONE

---

NMP-Portal/NMP-Portal/Views/Farm/Address.cshtml
NMP-Portal/NMP-Portal/Views/Farm/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Farm/ClimatePostCode.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Country.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Elevation.cshtml
NMP-Portal/NMP-Portal/Views/Farm/FarmRemove.cshtml
NMP-Portal/NMP-Portal/Views/Farm/FarmingRules.cshtml
NMP-Portal/NMP-Portal/Views/Farm/LastHarvestYear.cshtml
NMP-Portal/NMP-Portal/Views/Farm/ManualAddress.cshtml
NMP-Portal/NMP-Portal/Views/Farm/NVZ.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Name.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Organic.cshtml
NMP-Portal/NMP-Portal/Views/Farm/PostCode.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Rainfall.cshtml
NMP-Portal/NMP-Portal/Views/Farm/RainfallManual.cshtml

added hidden attribute on farm journey

Feature added hidden attribute on farm

---

NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Services/FertiliserManureService.cs
NMP-Portal/NMP-Portal/Services/IFertiliserManureService.cs
NMP-Portal/NMP-Portal/ViewModels/FertiliserManureViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/InOrgnaicManureDuration.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/NutrientValues.cshtml

Feature nmpt1236

---

NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Views/FertiliserManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/Fields.cshtml

Feature nmpt1265

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/FertiliserResponse.cs
NMP-Portal/NMP-Portal/Services/FertiliserManureService.cs
NMP-Portal/NMP-Portal/Services/IFertiliserManureService.cs
NMP-Portal/NMP-Portal/ViewModels/FertiliserManureViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/InOrgnaicManureDuration.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/NutrientValues.cshtml

nmpt1266, NMPT-1239 and NMPT1240 done

Feature nmpt1266

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Services/FertiliserManureService.cs
NMP-Portal/NMP-Portal/Services/IFertiliserManureService.cs
NMP-Portal/NMP-Portal/ViewModels/FertiliserManureViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/InOrgnaicManureDuration.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/NutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/RemoveFertiliser.cshtml

Feature nmpt1267

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Services/FertiliserManureService.cs
NMP-Portal/NMP-Portal/Services/IFertiliserManureService.cs
NMP-Portal/NMP-Portal/Services/IOrganicManureService.cs
NMP-Portal/NMP-Portal/Services/OrganicManureService.cs

changes for fertliser warning msg

Feature changes for fertliser warning msg

---

NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml

little change

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/ViewModels/FieldViewModel.cs
NMP-Portal/NMP-Portal/Views/Field/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Field/GrassLastThreeHarvestYear.cshtml
NMP-Portal/NMP-Portal/Views/Field/GrassManagementOptions.cshtml
NMP-Portal/NMP-Portal/Views/Field/GrassTypicalCuts.cshtml
NMP-Portal/NMP-Portal/Views/Field/HasGrassInLastThreeYear.cshtml
NMP-Portal/NMP-Portal/Views/Field/HasGreaterThan30PercentClover.cshtml
NMP-Portal/NMP-Portal/Views/Field/SoilNitrogenSupplyItems.cshtml

NMPT-1300 and NMPT-1301 done

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Views/FertiliserManure/InOrgnaicManureDuration.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/NutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Field/CropTypes.cshtml

little changes
1. warning msg banner width issue (resolved).
2. Parabhakar pointed out the issue while copying the field (resolved).

Feature nmpt1300

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs

added areaSpread and ManureQuantity

added areaSpread and ManureQuantity

---

NMP-Portal/NMP-Portal/Views/OrganicManure/ApplicationRateMethod.cshtml

Feature nmpt1243

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/CancelViewModel.cs
NMP-Portal/NMP-Portal/ViewModels/PlanViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/AnotherCrop.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Cancel.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropFields.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropGroupName.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoOne.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoTwo.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CurrentSward.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Defoliation.cshtml
NMP-Portal/NMP-Portal/Views/Crop/DefoliationSequence.cshtml
NMP-Portal/NMP-Portal/Views/Crop/DryMatterYield.cshtml
NMP-Portal/NMP-Portal/Views/Crop/GrassGrowthClass.cshtml
NMP-Portal/NMP-Portal/Views/Crop/GrassManagement.cshtml
NMP-Portal/NMP-Portal/Views/Crop/GrassSeason.cshtml
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearForPlan.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDate.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDateQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SwardType.cshtml
NMP-Portal/NMP-Portal/Views/Crop/VarietyName.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Yield.cshtml
NMP-Portal/NMP-Portal/Views/Crop/YieldQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Shared/_CancelConfirmation.cshtml

Feature nmpt1270

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/FarmViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/Cancel.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropGroupName.cshtml
NMP-Portal/NMP-Portal/Views/Crop/UpdateCropGroupNameCheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/VarietyName.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Address.cshtml
NMP-Portal/NMP-Portal/Views/Farm/AddressNotFound.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Cancel.cshtml
NMP-Portal/NMP-Portal/Views/Farm/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Farm/ClimatePostCode.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Country.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Elevation.cshtml
NMP-Portal/NMP-Portal/Views/Farm/FarmingRules.cshtml
NMP-Portal/NMP-Portal/Views/Farm/LastHarvestYear.cshtml
NMP-Portal/NMP-Portal/Views/Farm/NVZ.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Name.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Organic.cshtml
NMP-Portal/NMP-Portal/Views/Farm/PostCode.cshtml
NMP-Portal/NMP-Portal/Views/Farm/Rainfall.cshtml
NMP-Portal/NMP-Portal/Views/Farm/RainfallManual.cshtml
NMP-Portal/NMP-Portal/Views/Shared/_CancelConfirmation.cshtml

Faeture nmpt1304

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Views/Crop/AnotherCrop.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropFields.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoOne.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoTwo.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDate.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDateQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Yield.cshtml
NMP-Portal/NMP-Portal/Views/Crop/YieldQuestion.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/AdjustmentValue.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/CalculateNitrogenInCurrentCropQuestion.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/CalculateSoilNitrogenMineralisation.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/CropHeight.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/EstimateOfNitrogenMineralisationQuestion.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/GreenAreaIndex.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/GreenAreaIndexOrCropHeightQuestion.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/NumberOfShoots.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/RemoveSnsAnalysis.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/SampleDepth.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/SoilMineralNitrogenAnalysisResults.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/SoilNitrogenSupplyIndex.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/SoilOrganicMatter.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/SoilSampleDate.cshtml

bug resolved and applied hidden attribute on views

Feature bug on crop

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs

little modification for second crop

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml

date was changing to previous date after update

bug fixed application date and drainage end date

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Models/Crop.cs
NMP-Portal/NMP-Portal/Models/HarvestYearPlanFields.cs
NMP-Portal/NMP-Portal/Models/ManagementPeriod.cs
NMP-Portal/NMP-Portal/ServiceResponses/CropDetailResponse.cs
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml

Feature nmpt1229

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs

Feature bug on crop for second crop

---

NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Enums/ReportType.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/ReportViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/Report/ExportFields.cshtml
NMP-Portal/NMP-Portal/Views/Report/ReportType.cshtml

nmpt-1127 DONE

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/RecommendationHeader.cs
NMP-Portal/NMP-Portal/ViewModels/CropViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml

Feature nmpt1232

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml

applied code that on dev branch (BUG NMPT1361)

applied code that on dev branch

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Services/CropService.cs
NMP-Portal/NMP-Portal/Services/ICropService.cs
NMP-Portal/NMP-Portal/ViewModels/PlanViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/AnotherCrop.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Cancel.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropFields.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropGroupName.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoOne.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoTwo.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CurrentSward.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Defoliation.cshtml
NMP-Portal/NMP-Portal/Views/Crop/DefoliationSequence.cshtml
NMP-Portal/NMP-Portal/Views/Crop/DryMatterYield.cshtml
NMP-Portal/NMP-Portal/Views/Crop/GrassGrowthClass.cshtml
NMP-Portal/NMP-Portal/Views/Crop/GrassManagement.cshtml
NMP-Portal/NMP-Portal/Views/Crop/GrassSeason.cshtml
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearForPlan.cshtml
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDate.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDateQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SwardType.cshtml
NMP-Portal/NMP-Portal/Views/Crop/UpdateCropGroupNameCheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/VarietyName.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Yield.cshtml
NMP-Portal/NMP-Portal/Views/Crop/YieldQuestion.cshtml

NMPT-1327, NMPT1317,NMPT1364,NMPT-1365,NMPT-1328 done

Feature nmpt1328

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/ServiceResponses/HarvestYearPlanResponse.cs
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDate.cshtml
NMP-Portal/NMP-Portal/Views/Farm/FarmRemove.cshtml

NMPT-1329,NMPT-1318,NMPT-1366,NMPT-1367 USER STORIES DONE..

Feature nmpt1329

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Views/Crop/AnotherCrop.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Cancel.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropFields.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoOne.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoTwo.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CurrentSward.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Defoliation.cshtml
NMP-Portal/NMP-Portal/Views/Crop/DefoliationSequence.cshtml
NMP-Portal/NMP-Portal/Views/Crop/DryMatterYield.cshtml
NMP-Portal/NMP-Portal/Views/Crop/GrassGrowthClass.cshtml
NMP-Portal/NMP-Portal/Views/Crop/GrassManagement.cshtml
NMP-Portal/NMP-Portal/Views/Crop/GrassSeason.cshtml
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearForPlan.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml
NMP-Portal/NMP-Portal/Views/Crop/RemoveCrop.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDate.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDateQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SwardType.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Yield.cshtml
NMP-Portal/NMP-Portal/Views/Crop/YieldQuestion.cshtml

NMPT-1316,NMPT-1317,Bug-1376 done

Feature nmpt1316

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Services/CropService.cs
NMP-Portal/NMP-Portal/Services/ICropService.cs
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml

NMPT-1292, NMPT-1381,NMPT1222-NMPT-1223 done

Feature changes for crop t ype and field

---

NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Models/FertiliserManure.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Services/CropService.cs
NMP-Portal/NMP-Portal/Services/ICropService.cs
NMP-Portal/NMP-Portal/ViewModels/FertiliserManureViewModel.cs
NMP-Portal/NMP-Portal/ViewModels/OrganicManureViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/Cancel.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/Defoliation.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/InOrgnaicManureDuration.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/IsSameDefoliationForAll.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/NutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/Defoliation.cshtml

Feature nmpt1384

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Views/Crop/CropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/Defoliation.cshtml

Feature nmpt1406(bug)

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/Defoliation.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/IsSameDefoliationForAll.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/NutrientValues.cshtml

update fertiliser NMPT-1386 done

Feature update fertiliser

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Services/OrganicManureService.cs

Feature bug1412

---

NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/NMP-Portal.csproj
NMP-Portal/NMP-Portal/ViewModels/FertiliserManureViewModel.cs
NMP-Portal/NMP-Portal/Views/FertiliserManure/Cancel.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/Defoliation.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/DoubleCrop.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/FieldGroup.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/Fields.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/InOrgnaicManureDuration.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/IsSameDefoliationForAll.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/NutrientValues.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/RemoveFertiliser.cshtml

Feature nmpt1410

---

NMP-Portal/NMP-Portal/Controllers/SnsAnalysisController.cs
NMP-Portal/NMP-Portal/ViewModels/SnsAnalysisViewModel.cs
NMP-Portal/NMP-Portal/Views/SnsAnalysis/AdjustmentValue.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/CalculateNitrogenInCurrentCropQuestion.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/CalculateSoilNitrogenMineralisation.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/Cancel.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/CropHeight.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/EstimateOfNitrogenMineralisationQuestion.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/GreenAreaIndex.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/GreenAreaIndexOrCropHeightQuestion.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/NumberOfShoots.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/SampleDepth.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/SoilMineralNitrogenAnalysisResults.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/SoilNitrogenSupplyIndex.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/SoilOrganicMatter.cshtml
NMP-Portal/NMP-Portal/Views/SnsAnalysis/SoilSampleDate.cshtml

Feature nmpt1391

---

NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/RemoveOrganicManure.cshtml

NMPT-1434 done

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs

some changes for Update organic manure

Feature nmpt1284

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Services/CropService.cs
NMP-Portal/NMP-Portal/Services/ICropService.cs
NMP-Portal/NMP-Portal/Views/Report/NMaxReport.cshtml

changes for Update Crop and filtered Crop type listed for report.

Feature nmpt1289

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Report/NMaxReport.cshtml

Feature nmpt1288

---

NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/NMaxReportResponse.cs
NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml
NMP-Portal/NMP-Portal/Views/Report/NMaxReport.cshtml

nmpt1325, nmpt1326, nmpt1291 done

Feature nmpt1325

---

NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml
NMP-Portal/NMP-Portal/Views/Report/NMaxReport.cshtml

Feature nmpt1290

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/NitrogenApplicationsForNMaxReportResponse.cs
NMP-Portal/NMP-Portal/Services/FertiliserManureService.cs
NMP-Portal/NMP-Portal/Services/IFertiliserManureService.cs
NMP-Portal/NMP-Portal/Services/IOrganicManureService.cs
NMP-Portal/NMP-Portal/Services/OrganicManureService.cs
NMP-Portal/NMP-Portal/Views/Report/NMaxReport.cshtml

NMPT-1462 and NMPT-1463 done

---

NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/AboutService/Index.cshtml
NMP-Portal/NMP-Portal/Views/ReleaseSchedule/Index.cshtml

Feature nmpt1460

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs

changes for NMPT-1463

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Models/OrganicManure.cs
NMP-Portal/NMP-Portal/Models/OrganicManureUpdateData.cs
NMP-Portal/NMP-Portal/Views/AcceptTerms/_TermsOfUsePartial.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml

Feature nmpt1507

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Views/Crop/AnotherCrop.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Cancel.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CheckYourPlanData.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropFields.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropGroupName.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropGroups.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoOne.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoTwo.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropTypes.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CurrentSward.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Defoliation.cshtml
NMP-Portal/NMP-Portal/Views/Crop/DefoliationSequence.cshtml
NMP-Portal/NMP-Portal/Views/Crop/DryMatterYield.cshtml
NMP-Portal/NMP-Portal/Views/Crop/GrassGrowthClass.cshtml
NMP-Portal/NMP-Portal/Views/Crop/GrassManagement.cshtml
NMP-Portal/NMP-Portal/Views/Crop/GrassSeason.cshtml
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearForPlan.cshtml
NMP-Portal/NMP-Portal/Views/Crop/RemoveCrop.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDate.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDateQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SwardType.cshtml
NMP-Portal/NMP-Portal/Views/Crop/UpdateCropGroupNameCheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/VarietyName.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Yield.cshtml
NMP-Portal/NMP-Portal/Views/Crop/YieldQuestion.cshtml

This reverts commit 8e0e94244ba5c0ec6eea3570c7d7f863fbdf7765.

bug NMPT-1536 resolved

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/ReportViewModel.cs
NMP-Portal/NMP-Portal/Views/Crop/HarvestYearOverview.cshtml
NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml
NMP-Portal/NMP-Portal/Views/Report/ExportFieldsOrCropType.cshtml
NMP-Portal/NMP-Portal/Views/Report/FieldAndPlanReports.cshtml
NMP-Portal/NMP-Portal/Views/Report/NVZComplianceReports.cshtml
NMP-Portal/NMP-Portal/Views/Report/ReportOptions.cshtml
NMP-Portal/NMP-Portal/Views/Report/Year.cshtml

nmpt1498, nmpt1495,Nmpt1497 done

Feature nmpt1498

---

NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Farm/FarmSummary.cshtml
NMP-Portal/NMP-Portal/Views/Report/ExportFieldsOrCropType.cshtml
NMP-Portal/NMP-Portal/Views/Report/Year.cshtml

Feature nmpt1502

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/Defoliation.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/Defoliation.cshtml
NMP-Portal/NMP-Portal/Views/Report/NMaxReport.cshtml

Feature issue in grass base plan

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Services/CropService.cs
NMP-Portal/NMP-Portal/Services/ICropService.cs

changes for grass

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs

yield is null

---

NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/ReportViewModel.cs
NMP-Portal/NMP-Portal/Views/Report/ExportFieldsOrCropType.cshtml
NMP-Portal/NMP-Portal/Views/Report/FarmAreaForLivestockManure.cshtml
NMP-Portal/NMP-Portal/Views/Report/FieldAndPlanReports.cshtml
NMP-Portal/NMP-Portal/Views/Report/ImportExportOption.cshtml
NMP-Portal/NMP-Portal/Views/Report/IsGrasslandDerogation.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockImportExportDate.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockManureNitrogenReportChecklist.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockNutrientValue.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockQuantity.cshtml
NMP-Portal/NMP-Portal/Views/Report/ManureType.cshtml
NMP-Portal/NMP-Portal/Views/Report/NVZComplianceReports.cshtml
NMP-Portal/NMP-Portal/Views/Report/ReportOptions.cshtml
NMP-Portal/NMP-Portal/Views/Report/ReportType.cshtml
NMP-Portal/NMP-Portal/Views/Report/Year.cshtml

Feature nmpt1421

---

NMP-Portal/NMP-Portal/Controllers/FarmController.cs
NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Models/NutrientsLoadingManures.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Services/IReportService.cs
NMP-Portal/NMP-Portal/Services/ReportService.cs
NMP-Portal/NMP-Portal/ViewModels/ReportViewModel.cs
NMP-Portal/NMP-Portal/Views/Farm/FarmSummary.cshtml
NMP-Portal/NMP-Portal/Views/Report/UpdateImportExport.cshtml
NMP-Portal/NMP-Portal/Views/Report/UpdateLivestockImportExport.cshtml

Update Import Export screen changes

Feature update page for import export

---

NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Views/Report/LivestockManureNitrogenReportChecklist.cshtml

little changes for import export

Feature little changes

---

NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Views/Report/LivestockImportExportCheckAnswer.cshtml

Feature build error

---

NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/ReportViewModel.cs
NMP-Portal/NMP-Portal/Views/Report/Cancel.cshtml
NMP-Portal/NMP-Portal/Views/Report/ExportFieldsOrCropType.cshtml
NMP-Portal/NMP-Portal/Views/Report/FarmAreaForLivestockManure.cshtml
NMP-Portal/NMP-Portal/Views/Report/ImportExportOption.cshtml
NMP-Portal/NMP-Portal/Views/Report/IsAnyLivestock.cshtml
NMP-Portal/NMP-Portal/Views/Report/IsGrasslandDerogation.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockComment.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockDefaultNutrientValue.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockGroup.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockImportExportCheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockImportExportDate.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockImportExportQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockManualNutrientValue.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockManureNitrogenReportChecklist.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockQuantity.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockReceiver.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockType.cshtml
NMP-Portal/NMP-Portal/Views/Report/ManageImportExport.cshtml
NMP-Portal/NMP-Portal/Views/Report/ManureGroup.cshtml
NMP-Portal/NMP-Portal/Views/Report/ManureType.cshtml
NMP-Portal/NMP-Portal/Views/Report/NVZComplianceReports.cshtml
NMP-Portal/NMP-Portal/Views/Report/OtherMaterialName.cshtml
NMP-Portal/NMP-Portal/Views/Report/ReportOptions.cshtml
NMP-Portal/NMP-Portal/Views/Report/ReportType.cshtml
NMP-Portal/NMP-Portal/Views/Report/Year.cshtml

NMPT-1646, NMPT-1655, NMPT-1419 done

Feature nmpt1646

---

NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/OrganicManure/IncorporationDelay.cshtml

Content correction

---

NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Services/IReportService.cs
NMP-Portal/NMP-Portal/Services/ReportService.cs
NMP-Portal/NMP-Portal/ViewModels/ReportViewModel.cs
NMP-Portal/NMP-Portal/Views/Report/DeleteLivestockImportExport.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockImportExportCheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockManureNitrogenReportChecklist.cshtml
NMP-Portal/NMP-Portal/Views/Report/UpdateLivestockImportExport.cshtml

Feature nmpt1432

---

NMP-Portal/NMP-Portal/Views/Crop/Recommendations.cshtml
NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml

done NMPT-1656

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs

Feature nmpt1656

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Views/Crop/CropGroupName.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropGroups.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml

BUGs
NMPT-1750
NMPT-1749
NMPT-1743
NMPT-1737
NMPY-1738
NMPT-1741 
resolved

Feature nmpt1691

---

NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Models/NutrientsLoadingManures.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Report/LivestockManureNFarmLimitReport.cshtml
NMP-Portal/NMP-Portal/wwwroot/assets/stylesheets/application.css

import export stories of livestock report done

Feature import export fo livestock report

---

NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/FertiliserManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/FertiliserManure/DoubleCrop.cshtml
NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml

Feature nmpt 1766 and nmpt 1746

---

NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/ServiceResponses/NMaxLimitReportResponse.cs
NMP-Portal/NMP-Portal/ServiceResponses/NitrogenApplicationsForNMaxReportResponse.cs
NMP-Portal/NMP-Portal/Views/FertiliserManure/CheckAnswer.cshtml

nmpt 1777 bug resolve for fertiliser

Feature nmpt 1777

---

NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Views/FertiliserManure/Defoliation.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/OrganicManure/Defoliation.cshtml

Feature organic manure issue resolved

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/OrganicManure/DefaultNutrientValues.cshtml

Feature nmpt 1800

---

NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ServiceResponses/FieldAndCropReportResponse.cs
NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml
NMP-Portal/NMP-Portal/Views/Report/NMaxReport.cshtml

Feature nmpt1807 and nmpt1798

---

NMP-Portal/NMP-Portal/Views/Report/CropAndFieldManagement.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockCheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockManureNFarmLimitReport.cshtml
NMP-Portal/NMP-Portal/Views/Report/ManageLivestock.cshtml

NMPT-1815,NMPT-1816,NMPT-1820 done

NMPT-1815,NMPT-1816,NMPT-1820 done

---

NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Views/Report/LivestockCheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockGroup.cshtml
NMP-Portal/NMP-Portal/Views/Report/ManageLivestock.cshtml

Feature bug raised by mark

---

NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Enums/MaterialState.cs
NMP-Portal/NMP-Portal/Enums/StorageTypes.cs
NMP-Portal/NMP-Portal/Helpers/APIURLHelper.cs
NMP-Portal/NMP-Portal/Models/StoreCapacity.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Services/IReportService.cs
NMP-Portal/NMP-Portal/Services/ReportService.cs
NMP-Portal/NMP-Portal/Views/Report/ManageStorageCapacity.cshtml

Feature nmpt1786

---

NMP-Portal/NMP-Portal/Views/Report/LivestockManureNFarmLimitReport.cshtml

Feature nmpt1840 and nmpt1841

---

NMP-Portal/NMP-Portal/Controllers/ReportController.cs

NMPT-1839 done

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Models/HarvestYear.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Crop/PlansAndRecordsOverview.cshtml
NMP-Portal/NMP-Portal/Views/Field/SulphurDeficient.cshtml
NMP-Portal/NMP-Portal/Views/SoilAnalysis/SulphurDeficient.cshtml

Feature nmpt1887 and nmpt1877

---

NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Report/LivestockCheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockNumberQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockNumbersMonthly.cshtml
NMP-Portal/NMP-Portal/Views/Report/ManageLivestock.cshtml

almost all live stock user story done

ALMOST ALL done

---

NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx

Feature livestock nutrient stories

---

NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs

Feature nmpt1960

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml

Feature nmpt1979

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/StorageCapacityController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/ViewModels/StorageCapacityViewModel.cs
NMP-Portal/NMP-Portal/Views/StorageCapacity/BankSlopeAngle.cshtml
NMP-Portal/NMP-Portal/Views/StorageCapacity/Cancel.cshtml
NMP-Portal/NMP-Portal/Views/StorageCapacity/CopyExistingManureStorage.cshtml
NMP-Portal/NMP-Portal/Views/StorageCapacity/CopyExistingManureStorageYearList.cshtml
NMP-Portal/NMP-Portal/Views/StorageCapacity/Dimensions.cshtml
NMP-Portal/NMP-Portal/Views/StorageCapacity/MaterialStates.cshtml
NMP-Portal/NMP-Portal/Views/StorageCapacity/SlopeQuestion.cshtml
NMP-Portal/NMP-Portal/Views/StorageCapacity/StorageBagCapacity.cshtml
NMP-Portal/NMP-Portal/Views/StorageCapacity/StorageCapacityManagement.cshtml
NMP-Portal/NMP-Portal/Views/StorageCapacity/StorageTypes.cshtml
NMP-Portal/NMP-Portal/Views/StorageCapacity/StoreName.cshtml
NMP-Portal/NMP-Portal/Views/StorageCapacity/WeightCapacity.cshtml

Feature nmpt1911

---

NMP-Portal/NMP-Portal/Controllers/ReportController.cs
NMP-Portal/NMP-Portal/Views/Report/AverageNumber.cshtml
NMP-Portal/NMP-Portal/Views/Report/Cancel.cshtml
NMP-Portal/NMP-Portal/Views/Report/IsAnyLivestockNumber.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockCheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockGroup.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockNumberQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockNumbersMonthly.cshtml
NMP-Portal/NMP-Portal/Views/Report/LivestockType.cshtml
NMP-Portal/NMP-Portal/Views/Report/ManageLivestock.cshtml
NMP-Portal/NMP-Portal/Views/Report/NitrogenStandard.cshtml
NMP-Portal/NMP-Portal/Views/Report/NonGrazingLivestockAverageNumber.cshtml
NMP-Portal/NMP-Portal/Views/Report/Occupancy.cshtml
NMP-Portal/NMP-Portal/Views/Report/OccupancyAndStandard.cshtml

livestock related issue resolve

Feature livestock related issue resolve

---

NMP-Portal/NMP-Portal/Controllers/CropController.cs
NMP-Portal/NMP-Portal/Controllers/FertiliserManureController.cs
NMP-Portal/NMP-Portal/Controllers/OrganicManureController.cs
NMP-Portal/NMP-Portal/Enums/YieldQuestion.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoOne.cshtml
NMP-Portal/NMP-Portal/Views/Crop/CropInfoTwo.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Yield.cshtml
NMP-Portal/NMP-Portal/Views/Crop/YieldQuestion.cshtml

Feature nmpt1985

---

NMP-Portal/NMP-Portal/Controllers/FieldController.cs
NMP-Portal/NMP-Portal/Resources/Resource.Designer.cs
NMP-Portal/NMP-Portal/Resources/Resource.resx
NMP-Portal/NMP-Portal/Views/Field/FieldSoilAnalysisDetail.cshtml

done NMPT-1949

---

NMP-Portal/NMP-Portal/Views/Crop/CheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDate.cshtml
NMP-Portal/NMP-Portal/Views/Crop/SowingDateQuestion.cshtml
NMP-Portal/NMP-Portal/Views/Crop/UpdateCropGroupNameCheckAnswer.cshtml
NMP-Portal/NMP-Portal/Views/Crop/Yield.cshtml
NMP-Portal/NMP-Portal/Views/Crop/YieldQuestion.cshtml
NMP-Portal/NMP-Portal/Views/StorageCapacity/OrganicMaterialStorageNotAvailable.cshtml

Feature nmpt1984 again
